### ISSUE TITLE
Add links to open quickstarts in che.openshift.io

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus-quickstarts#281]
che 7 has a new notion of [devfile.yml](https://www.eclipse.org/che/docs/che-7/making-a-workspace-portable-using-a-devfile/) which we in *theory* should be able to add to the quickstarts to  give links to [che.openshift.io](https://che.openshift.io/f?url=https://github.com/quarkusio/quarkus-quickstarts/tree/master/getting-started) that setup a environment to edit/run most getting started projects.

This issue is to discuss this with Che team and try find what is possible and what we might need to avoid doing too much manual work.

For now biggest issues I've found:

- [ ] devfile *must* be in root which is counter to layout common to quickstarts where there are multiple projects and you don't want all opened/imported.
- [ ] devfile have a lot of absolute references to git repos making it impossible to do your own git clone and use them as your own reference
- [ ] tasks/commands have absolute references to how mvn command are run rather than looking up contextually to where you are (i.e. instead of '/project/quickstarts/getting-started' I would like to have a way to say 'nearest parent from current editor/context that has a pom.xml'

**Comment by maxandersen** [comment]
to begin with we could start with explicit devfile.yml for the getting-started example.

**Comment by maxandersen** [comment]
so che.openshift.io/f?url=https://github.com/maxandersen/quarkus-quickstarts/tree/che works and checks out the project as expected as long as there is *no* devfile.yaml.

If I put a devfile.yaml in there it stops checking out the project and seem to force me to have an absolute reference like: 

```
projects:
  -
    name: console-java-simple
    source:
      type: git
      location: "https://github.com/che-samples/console-java-simple.git"projects:
  -
    name: console-java-simple
    source:
      type: git
      location: "https://github.com/maxandersen/quarkus-quickstarts.git"
```

That is counter intuitive and not very flexible.
